---
name: Build

on:
  pull_request:
  push:
    branches:
      - master
  schedule:
    - cron: "10 1 * * 0"

jobs:
  # If on master branch, build and release image.
  release:
    name: Release
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build go app multiarch and push image.
        uses: docker/build-push-action@v2
        with:
          context: go
          file: go/Dockerfile
          platforms: linux/amd64, linux/arm64
          push: true
          tags: ${{ github.repository }}:go
      
      - name: Build java app multiarch and push image.
        uses: docker/build-push-action@v2
        with:
          context: java
          file: java/Dockerfile
          platforms: linux/amd64, linux/arm64
          push: true
          tags: ${{ github.repository }}:java
          target: multi-line-app
